# Generated by Django 4.0.1 on 2022-06-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Customer_id', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('Address', models.CharField(max_length=60)),
                ('Account_number', models.CharField(max_length=20)),
                ('Phone_number', models.IntegerField()),
            ],
        ),
    ]
